### ISSUE TITLE
 Wireframe

### ISSUE THREAD

**Issue by Daniloel** [Daniloel/Projeto-Integrador-2021-2-Grupo3#1]
Desenvolvimento da Wireframe e inicio do prototipo.

**Comment by LeoAdlerr** [comment]
Teste

**Comment by LeoAdlerr** [comment]
[https://www.figma.com/file/AFlTRiQ9bOnQnYq80W2YWt/Api1-2021-team-library?node-id=0%3A1](url)

**Comment by LeoAdlerr** [comment]
Wireframe terminado, encontra-se no readme do projeto.
